<?xml version="1.0" encoding="utf-8"?>
<Database Name="Products" Class="PhoneDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=Products;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ProductsConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Banners" Member="Banners">
    <Type Name="Banner">
      <Column Name="BannerID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BannerName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Link" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PostDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Promotions" Member="Promotions">
    <Type Name="Promotion">
      <Column Name="PromotionID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PhoneID" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="Percentage" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Phone_Promotion" Member="Phone" ThisKey="PhoneID" Type="Phone" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Customer_Order" Member="Orders" OtherKey="CustomerID" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.Firms" Member="Firms">
    <Type Name="Firm">
      <Column Name="FirmID" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirmName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Firm_Phone" Member="Phones" OtherKey="FirmID" Type="Phone" />
    </Type>
  </Table>
  <Table Name="dbo.Order_Details" Member="Order_Details">
    <Type Name="Order_Detail">
      <Column Name="OrderID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PhoneID" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SalePrice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Order_Order_Detail" Member="Order" ThisKey="OrderID" Type="Order" IsForeignKey="true" />
      <Association Name="Phone_Order_Detail" Member="Phone" ThisKey="PhoneID" Type="Phone" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="OrderID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="RequireDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShippedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShipAddress" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Total" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="Order_Order_Detail" Member="Order_Details" OtherKey="OrderID" Type="Order_Detail" />
      <Association Name="Customer_Order" Member="Customer" ThisKey="CustomerID" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Phones" Member="Phones">
    <Type Name="Phone">
      <Column Name="PhoneID" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PhoneName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FirmID" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ImportDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Quantity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Warranty" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FamousInfomation" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Design" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Languages" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Sound" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Memory" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="WebConnection" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Browsers" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="Camera" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MusicPlayer" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MoviesPlayer" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Games" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
      <Column Name="OrtherInfomations" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Battery" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NumVisited" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Phone_Promotion" Member="Promotions" OtherKey="PhoneID" Type="Promotion" />
      <Association Name="Phone_Order_Detail" Member="Order_Details" OtherKey="PhoneID" Type="Order_Detail" />
      <Association Name="Phone_Poll" Member="Polls" OtherKey="PhoneID" Type="Poll" />
      <Association Name="Firm_Phone" Member="Firm" ThisKey="FirmID" Type="Firm" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Polls" Member="Polls">
    <Type Name="Poll">
      <Column Name="PollID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PhoneID" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="Commentator" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="PostDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VoteCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Phone_Poll" Member="Phone" ThisKey="PhoneID" Type="Phone" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.AdvancedSearch" Method="AdvancedSearch">
    <Parameter Name="Design" Parameter="design" Type="System.String" DbType="NVarChar(450)" />
    <Parameter Name="Memory" Parameter="memory" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="WebConnection" Parameter="webConnection" Type="System.String" DbType="NVarChar(400)" />
    <Parameter Name="Browsers" Parameter="browsers" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="Camera" Parameter="camera" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="MusicPlayer" Parameter="musicPlayer" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="MoviesPlayer" Parameter="moviesPlayer" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="currpage" Type="System.Int32" DbType="Int" />
    <Parameter Name="recordperpage" Type="System.Int32" DbType="Int" />
    <Parameter Name="totalrecord" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="AdvancedSearchResult">
      <Column Name="FamousInfomation" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UpdateQuantityProduct" Method="UpdateQuantityProduct">
    <Parameter Name="PhoneID" Parameter="phoneID" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="QuantitySale" Parameter="quantitySale" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteBanner" Method="DeleteBanner">
    <Parameter Name="BannerID" Parameter="bannerID" Type="System.String" DbType="VarChar(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteCustomer" Method="DeleteCustomer">
    <Parameter Name="CusID" Parameter="cusID" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteFirm" Method="DeleteFirm">
    <Parameter Name="FirmID" Parameter="firmID" Type="System.String" DbType="VarChar(3)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteOrder" Method="DeleteOrder">
    <Parameter Name="OrderID" Parameter="orderID" Type="System.String" DbType="NChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeletePhone" Method="DeletePhone">
    <Parameter Name="PhoneID" Parameter="phoneID" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeletePoll" Method="DeletePoll">
    <Parameter Name="PollID" Parameter="pollID" Type="System.String" DbType="NChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeletePromotion" Method="DeletePromotion">
    <Parameter Name="PromotionID" Parameter="promotionID" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DisplayBanner" Method="DisplayBanner">
    <Parameter Name="Link" Parameter="link" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="currpage" Type="System.Int32" DbType="Int" />
    <Parameter Name="recordperpage" Type="System.Int32" DbType="Int" />
    <Parameter Name="totalrecord" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="DisplayBannerResult">
      <Column Name="BannerID" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BannerName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Link" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PostDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DisPlayFavouriteProduct" Method="DisPlayFavouriteProduct">
    <ElementType Name="DisPlayFavouriteProductResult">
      <Column Name="PhoneID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DisplaymMarketableProduct" Method="DisplaymMarketableProduct">
    <ElementType Name="DisplaymMarketableProductResult">
      <Column Name="PhoneID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DisplayNewProduct" Method="DisplayNewProduct">
    <ElementType Name="DisplayNewProductResult">
      <Column Name="PhoneID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DisplayOrderbyDate" Method="DisplayOrderbyDate">
    <Parameter Name="OrderDate" Parameter="orderDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="currpage" Type="System.Int32" DbType="Int" />
    <Parameter Name="recordperpage" Type="System.Int32" DbType="Int" />
    <Parameter Name="totalrecord" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="DisplayOrderbyDateResult">
      <Column Name="PhoneName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="OrderID" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ShipAddress" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SalePrice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DisplayPollperPhone" Method="DisplayPollperPhone">
    <Parameter Name="PhoneID" Parameter="phoneID" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="currpage" Type="System.Int32" DbType="Int" />
    <Parameter Name="recordperpage" Type="System.Int32" DbType="Int" />
    <Parameter Name="totalrecord" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="DisplayPollperPhoneResult">
      <Column Name="rowindex" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Commentator" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="PostDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VoteCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DisplayProductDetail" Method="DisplayProductDetail">
    <Parameter Name="PhoneName" Parameter="phoneName" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="currstatus" Type="System.String" DbType="VarChar(50)" Direction="InOut" />
    <ElementType Name="DisplayProductDetailResult">
      <Column Name="PhoneName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FirmName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Warranty" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FamousInfomation" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Design" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Languages" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Sound" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Memory" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="WebConnection" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Browsers" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="Camera" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MusicPlayer" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MoviesPlayer" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Games" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
      <Column Name="OrtherInfomations" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Battery" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetSameProducts" Method="GetSameProducts">
    <Parameter Name="FirmName" Parameter="firmName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PhoneName" Parameter="phoneName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="currpage" Type="System.Int32" DbType="Int" />
    <Parameter Name="recordperpage" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetSameProductsResult">
      <Column Name="rowindex" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PhoneName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.IncreaseBannerID" Method="IncreaseBannerID">
    <Parameter Name="BannerID" Parameter="bannerID" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.IncreaseCusID" Method="IncreaseCusID">
    <Parameter Name="CusID" Parameter="cusID" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.IncreaseFirmID" Method="IncreaseFirmID">
    <Parameter Name="FirmID" Parameter="firmID" Type="System.String" DbType="VarChar(3)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.IncreaseOrderID" Method="IncreaseOrderID">
    <Parameter Name="OrderID" Parameter="orderID" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.IncreasePhoneID" Method="IncreasePhoneID">
    <Parameter Name="FirmID" Parameter="firmID" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="PhoneID" Parameter="phoneID" Type="System.String" DbType="VarChar(6)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.IncreasePollID" Method="IncreasePollID">
    <Parameter Name="PollID" Parameter="pollID" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.IncreasePromotionID" Method="IncreasePromotionID">
    <Parameter Name="PromotionID" Parameter="promotionID" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertBanner" Method="InsertBanner">
    <Parameter Name="BannerName" Parameter="bannerName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Picture" Parameter="picture" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="Link" Parameter="link" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="PostDate" Parameter="postDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Location" Parameter="location" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertCustomer" Method="InsertCustomer">
    <Parameter Name="CusName" Parameter="cusName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="Number" Parameter="number" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertFirm" Method="InsertFirm">
    <Parameter Name="FirmName" Parameter="firmName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Picture" Parameter="picture" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertOrder" Method="InsertOrder">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="Number" Parameter="number" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="OrderDate" Parameter="orderDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="RequireDate" Parameter="requireDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ShippedDate" Parameter="shippedDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ShipAddress" Parameter="shipAddress" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="total" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertOrder_Detail" Method="InsertOrder_Detail">
    <Parameter Name="OrderID" Parameter="orderID" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="PhoneID" Parameter="phoneID" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="Quantity" Parameter="quantity" Type="System.Int32" DbType="Int" />
    <Parameter Name="SalePrice" Parameter="salePrice" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertPhone" Method="InsertPhone">
    <Parameter Name="PhoneID" Parameter="phoneID" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="PhoneName" Parameter="phoneName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="FirmName" Parameter="firmName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="FirmID" Parameter="firmID" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="Picture" Parameter="picture" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="ImportDate" Parameter="importDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Quantity" Parameter="quantity" Type="System.Int32" DbType="Int" />
    <Parameter Name="Price" Parameter="price" Type="System.Double" DbType="Float" />
    <Parameter Name="Warranty" Parameter="warranty" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="FamousInfo" Parameter="famousInfo" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="Design" Parameter="design" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="Languages" Parameter="languages" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="Sound" Parameter="sound" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Memory" Parameter="memory" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="WebConnection" Parameter="webConnection" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="Browser" Parameter="browser" Type="System.String" DbType="NVarChar(400)" />
    <Parameter Name="Camera" Parameter="camera" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Music" Parameter="music" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Movies" Parameter="movies" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Game" Parameter="game" Type="System.String" DbType="NVarChar(350)" />
    <Parameter Name="Orther" Parameter="orther" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="Battery" Parameter="battery" Type="System.String" DbType="NVarChar(500)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertPoll" Method="InsertPoll">
    <Parameter Name="PhoneID" Parameter="phoneID" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="Commentator" Parameter="commentator" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="PostDate" Parameter="postDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Comments" Parameter="comments" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="VoteCount" Parameter="voteCount" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertPromotion" Method="InsertPromotion">
    <Parameter Name="PhoneID" Parameter="phoneID" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="Percentage" Parameter="percentage" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SearchByName" Method="SearchByName">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="currpage" Type="System.Int32" DbType="Int" />
    <Parameter Name="recordperpage" Type="System.Int32" DbType="Int" />
    <Parameter Name="totalrecord" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="SearchByNameResult">
      <Column Name="rowindex" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PhoneName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SearchByPrice" Method="SearchByPrice">
    <Parameter Name="Min" Parameter="min" Type="System.Double" DbType="Float" />
    <Parameter Name="Max" Parameter="max" Type="System.Double" DbType="Float" />
    <Parameter Name="currpage" Type="System.Int32" DbType="Int" />
    <Parameter Name="recordperpage" Type="System.Int32" DbType="Int" />
    <ElementType Name="SearchByPriceResult">
      <Column Name="rowindex" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PhoneName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SearchCustomerByAddress" Method="SearchCustomerByAddress">
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(250)" />
    <ElementType Name="SearchCustomerByAddressResult">
      <Column Name="CustomerID" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SearchCustomerByName" Method="SearchCustomerByName">
    <Parameter Name="CusName" Parameter="cusName" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="SearchCustomerByNameResult">
      <Column Name="CustomerID" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SearchFirmByName" Method="SearchFirmByName">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="SearchFirmByNameResult">
      <Column Name="FirmID" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="FirmName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UpdateBanner" Method="UpdateBanner">
    <Parameter Name="BannerID" Parameter="bannerID" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="BannerName" Parameter="bannerName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Picture" Parameter="picture" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="Link" Parameter="link" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="PostDate" Parameter="postDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Location" Parameter="location" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateCustomer" Method="UpdateCustomer">
    <Parameter Name="CusID" Parameter="cusID" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="CusName" Parameter="cusName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="Number" Parameter="number" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateFirm" Method="UpdateFirm">
    <Parameter Name="FirmID" Parameter="firmID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="FirmName" Parameter="firmName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Picture" Parameter="picture" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NText" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateOrder" Method="UpdateOrder">
    <Parameter Name="OrderID" Parameter="orderID" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="CusID" Parameter="cusID" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="OrderDate" Parameter="orderDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="RequireDate" Parameter="requireDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ShippedDate" Parameter="shippedDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ShipAddress" Parameter="shipAddress" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="Note" Parameter="note" Type="System.String" DbType="NVarChar(500)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateOrder_Detail" Method="UpdateOrder_Detail">
    <Parameter Name="OrderID" Parameter="orderID" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="PhoneID" Parameter="phoneID" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="Quantity" Parameter="quantity" Type="System.Int32" DbType="Int" />
    <Parameter Name="SalePrice" Parameter="salePrice" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdatePhone" Method="UpdatePhone">
    <Parameter Name="PhoneID" Parameter="phoneID" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="PhoneName" Parameter="phoneName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="FirmID" Parameter="firmID" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="Picture" Parameter="picture" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="PostDate" Parameter="postDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Quantity" Parameter="quantity" Type="System.Int32" DbType="Int" />
    <Parameter Name="Price" Parameter="price" Type="System.Double" DbType="Float" />
    <Parameter Name="Warranty" Parameter="warranty" Type="System.Int32" DbType="Int" />
    <Parameter Name="FamousInfo" Parameter="famousInfo" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Design" Parameter="design" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="Languages" Parameter="languages" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Sound" Parameter="sound" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Memory" Parameter="memory" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="WebConnection" Parameter="webConnection" Type="System.String" DbType="NVarChar(400)" />
    <Parameter Name="Browser" Parameter="browser" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="Camera" Parameter="camera" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="Music" Parameter="music" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="Movies" Parameter="movies" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="Game" Parameter="game" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="Orther" Parameter="orther" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="Battery" Parameter="battery" Type="System.String" DbType="NVarChar(500)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdatePoll" Method="UpdatePoll">
    <Parameter Name="PollID" Parameter="pollID" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="PhoneID" Parameter="phoneID" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="VoteCount" Parameter="voteCount" Type="System.Int32" DbType="Int" />
    <Parameter Name="dateTime" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="comment" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdatePromotion" Method="UpdatePromotion">
    <Parameter Name="PromotionID" Parameter="promotionID" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="PhoneID" Parameter="phoneID" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="Percentage" Parameter="percentage" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SearchByFirm" Method="SearchByFirm">
    <Parameter Name="FirmName" Parameter="firmName" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="currpage" Type="System.Int32" DbType="Int" />
    <Parameter Name="recordperpage" Type="System.Int32" DbType="Int" />
    <ElementType Name="SearchByFirmResult">
      <Column Name="rowindex" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PhoneID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FirmID" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>